/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b3c4033007301e641e8b75d7f5ba10e4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "PstackAgent";
	}
	interface Env {
		AI: Ai;
		PstackAgent: DurableObjectNamespace<import("./src/server").PstackAgent>;
	}
}
interface Env extends Cloudflare.Env {}
